WearDrawers/Wearable/build.gradle
WearDrawers/Wearable/src/main/AndroidManifest.xml
WearDrawers/Wearable/src/main/java/com/example/android/wearable/wear/weardrawers/MainActivity.java
WearDrawers/gradle/wrapper/gradle-wrapper.properties

- Updates sample to use AppCompatActivity & AndroidX Fragments.
- Minor formatting updates.
Fixes #28

Update WearDrawers to use AppCompat

---

AlwaysOn/Wearable/build.gradle
DataLayer/Wearable/build.gradle
JumpingJack/Wearable/build.gradle
RuntimePermissionsWear/Wearable/build.gradle
SpeedTracker/Wearable/build.gradle
WatchFace/Application/build.gradle
WatchFace/Wearable/build.gradle
WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/AnalogComplicationWatchFaceService.java
WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/DigitalWatchFaceService.java
WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/InteractiveWatchFaceService.java
WearAccessibilityApp/Wearable/build.gradle
WearComplicationProvidersTestSuite/Wearable/build.gradle
WearDrawers/Wearable/build.gradle
WearHighBandwidthNetworking/Wearable/build.gradle
WearOAuth/app/build.gradle
WearSpeakerSample/wear/build.gradle
WearStandaloneGoogleSignIn/app/build.gradle
WearVerifyRemoteApp/Application/build.gradle
WearVerifyRemoteApp/Wearable/build.gradle
XYZTouristAttractions/Wearable/build.gradle

This also switches watch face samples to use hardware accelerated
canvas.

Update samples to use 2.7.0 wear support lib.

---

AlwaysOn/README.md

20 seconds between any updates to ~~conserving~~ conserve battery life

Fix typo in README

---

WearOAuth/app/build.gradle
WearOAuth/app/src/main/java/com/example/android/wearable/wear/wearoauth/WearOAuthActivity.java
WearOAuth/app/src/main/res/layout/layout.xml
WearOAuth/app/src/main/res/values/strings.xml

This is more a swap out to OkHttp then OAuth changes.

Updates OAuth to use OkHttp.

---

AlwaysOn/Wearable/src/main/res/layout/activity_main.xml
DataLayer/Wearable/src/main/res/layout/recycler_row_event_logging.xml
RuntimePermissionsWear/Wearable/src/main/res/layout/activity_main.xml
RuntimePermissionsWear/Wearable/src/main/res/layout/activity_request_permission_on_phone.xml
WatchFace/Wearable/src/main/res/layout/activity_digital_config.xml

The latter is deprecated in androidx.wear:wear 1.1.0

Use layout_boxedEdges attribute instead of boxedEdges.

---

WatchFace/Application/build.gradle
WatchFace/Application/src/main/java/com/example/android/wearable/watchface/DigitalWatchFaceCompanionConfigActivity.java
WatchFace/Application/src/main/java/com/example/android/wearable/watchface/OpenGLWatchFaceConfigActivity.java

Replacing usage of WatchFaceCompanion from WSL with new WatchFaceConfigIntentHelper from AndroidX

---

WearTilesKotlin/app/build.gradle
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/components/IconButton.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/fitness/FitnessTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/media/PlayNextSongTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileService.kt

* Moved all references to tiles.builders/tiles.readers to just tiles.
* Deprecated FontStyles calls moved to new format (static methods taking
a DeviceParameters instance).
* setAndroidResourceByResid updated to setAndroidResourceByResId.

Update to 1.0.0-alpha06 of Tiles library.

---

AlwaysOn/Wearable/build.gradle
AlwaysOn/build.gradle
AlwaysOn/gradle/wrapper/gradle-wrapper.properties

A small update to `AlwaysOn` that updates the Andoid Gradle Plugin and adds the Kotlin plugin, in preparation to convert to Kotlin.

[AlwaysOn] Update to allow conversion to Kotlin

---

AlwaysOn/Wearable/build.gradle
AlwaysOn/Wearable/src/androidTest/java/com/example/android/wearable/wear/alwayson/MainActivityTests.kt
AlwaysOn/Wearable/src/main/java/com/example/android/wearable/wear/alwayson/MainActivity.kt

Adds some basic instrumented tests for the `AlwaysOn` sample, checking that the views are updated in both ambient and active modes.

[AlwaysOn] Add instrumented tests

---

WearSpeakerSample/build.gradle
WearSpeakerSample/gradle/wrapper/gradle-wrapper.properties
WearSpeakerSample/wear/build.gradle

Prepares the Speaker sample to be converted from Java to Kotlin.

[Speaker] Add Kotlin plugin

---

WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/MainActivity.kt

Adds cleanup for the `TileUiClient` used to preview tiles.

[Tiles] Close TileUiClient

---

WearTilesKotlin/app/src/main/AndroidManifest.xml
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/components/IconButton.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/fitness/FitnessTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/media/PlayNextSongTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingRepo.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileService.kt
WearTilesKotlin/app/src/main/res/values/strings.xml

Adds content descriptions to the three sample tiles. I also made all buttons actually clickable with a no-op `LoadAction`.

[Tiles] Add content descriptions

---

README.md
WearSpeakerSample/README.md

Updates the Speaker sample documentation to reflect the conversion from Java to Kotlin.

[Speaker] Update documentation

---

WearVerifyRemoteApp/Wearable/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainWearActivity.kt

A small update to apply spotless to the `VerifyRemote` watch app.

[VerifyRemote] Watch app apply spotless checks

---

README.md
WearVerifyRemoteApp/README.md

Updates the docs for `VerifyRemote`, marking that it was converted from Java to Kotlin.

[VerifyRemote] Update docs

---

WearTilesKotlin/README.md

In my last PR I had copied the description from the original readme so I noticed its lowercase in here, too. #137

Update AndroidX capitalizations

---

AlwaysOnKotlin/Wearable/build.gradle

Updates `androidx` dependencies to latest for `AlwaysOn`

[AlwaysOn] Update dependencies

---

WearOAuth/oauth-device-grant/build.gradle
WearOAuth/oauth-device-grant/src/main/java/com/example/android/wearable/oauth/devicegrant/AuthDeviceGrantViewModel.kt
WearOAuth/oauth-pkce/build.gradle
WearOAuth/util/build.gradle

Updates dependencies for OAuth to latest.

[OAuth] Update dependencies

---

WearVerifyRemoteApp/Application/build.gradle
WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt
WearVerifyRemoteApp/Wearable/build.gradle
WearVerifyRemoteApp/Wearable/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainWearActivity.kt

Updates `androidx.wear` dependencies for `RuntimePermissions` to latest.

[RuntimePermissions] Update dependencies

---

WearTilesKotlin/app/build.gradle

Updates tiles to use the latest `androidx.wear` dependencies.

[Tiles] Update dependencies

---

WatchFaceAlphaKotlin/app/src/main/AndroidManifest.xml
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/AnalogWatchCanvasRenderer.kt
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/data/watchface/WatchFaceColorPalette.kt
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/editor/WatchFaceConfigActivity.kt
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/editor/WatchFaceConfigStateHolder.kt
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/utils/ComplicationUtils.kt
WatchFaceAlphaKotlin/app/src/main/java/com/example/android/wearable/alpha/utils/UserStyleSchemaUtils.kt
WatchFaceAlphaKotlin/app/src/main/res/layout/activity_watch_face_config.xml
WatchFaceAlphaKotlin/app/src/main/res/layout/watch_face_and_complications_preview.xml
WatchFaceAlphaKotlin/app/src/main/res/values/strings.xml

Adds support for editing the complications and fixes any rendering issues with changes to the complications.
Also, does some slight cleanup.

Adds edit support for the complications.

---

WearComplicationDataSourcesTestSuite/Wearable/build.gradle
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ComplicationToggleReceiver.kt
WearComplicationDataSourcesTestSuite/build.gradle

Updates complications dependencies to latest.

[Complications] Update dependencies

---

WearVerifyRemoteApp/Application/build.gradle
WearVerifyRemoteApp/Wearable/build.gradle
WearVerifyRemoteApp/build.gradle

Updates dependencies to latest for the VerifyRemote sample

[VerifyRemote] Update deps

---

WearOAuth/oauth-device-grant/build.gradle
WearOAuth/oauth-pkce/build.gradle

Update OAuth dependencies to latest.

[OAuth] Update to latest

---

WearVerifyRemoteApp/Application/build.gradle
WearVerifyRemoteApp/Wearable/build.gradle

Updates VerifyRemote to latest dependencies

[VerifyRemote] Update to latest dependencies

---

WearTilesKotlin/app/build.gradle

Updates Tiles to latest dependencies

[Tiles] Update to 1.0.0-rc01

---

WearComplicationDataSourcesTestSuite/Wearable/build.gradle

Updates ComplicationsDependencies to latest (`1.0.0-beta01`)

[Complications] Update to 1.0.0-beta01

---

RuntimePermissionsWear/Application/build.gradle
RuntimePermissionsWear/Wearable/build.gradle
RuntimePermissionsWear/build.gradle

Updates `RuntimePermissions` to latest dependencies.

[RuntimePermissions] Update to latest deps

---

WatchFaceAlphaKotlin/app/build.gradle
WatchFaceAlphaKotlin/build.gradle

Updates the watchface sample to the latest dependencies.

[WatchFace] Update to 1.0.0-rc01

---

AlwaysOnKotlin/Wearable/build.gradle
ComposeAdvanced/build.gradle
ComposeStarter/build.gradle
WearComplicationDataSourcesTestSuite/Wearable/build.gradle
WearOAuth/build.gradle
WearTilesKotlin/app/build.gradle
WearVerifyRemoteApp/Application/build.gradle
WearVerifyRemoteApp/Wearable/build.gradle
WearVerifyRemoteApp/build.gradle

A collection of dependency updates across most projects in the repo.

[All] Update dependencies

---

TimeText/timetext/build.gradle
TimeText/timetexttestsupport/build.gradle
TimeText/wear/build.gradle

Updates timetext dependencies to latest, and also cleans up a couple of the dependencies used.

[TimeText] Update deps

---

AlwaysOnKotlin/Wearable/build.gradle
AlwaysOnKotlin/Wearable/src/androidTest/java/com/example/android/wearable/wear/alwayson/MainActivityTests.kt

Updates AlwaysOn to kotlinx.coroutines 1.6.0, and also updates the tests to use the new kotlinx.coroutines test API.

Update to kotlinx.coroutines 1.6.0

---

ComposeAdvanced/app/build.gradle
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/MainActivity.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/CustomPositionIndicator.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/CustomTimeText.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/CustomVignette.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/WatchAppChip.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListScreen.kt
ComposeAdvanced/build.gradle
ComposeAdvanced/gradle/wrapper/gradle-wrapper.properties

Attempting to upgrade to Wear specific Previews where appropriate (full screen).

Update to Wear Specific Previews

---

WearTilesKotlin/app/build.gradle
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/CoroutinesTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/fitness/FitnessTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/media/PlayNextSongTileService.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileService.kt
gradle/libs.versions.toml

Run tileRequest and resourceRequest on Dispatchers.Main.
This avoid an observable behaviour change from TileService.

Use Main dispatcher in Tiles samples

---

ComposeAdvanced/app/build.gradle

Removing because this is not an annotation processor.

Remove inaccurate comment

---

WatchFaceKotlin/.google/packaging.yaml

Adds YAML file needed to show up in studio/DAC.

Adds yaml file for watch face sample (to show up in studio).

---

.github/workflows/AlwaysOnKotlin.yml
.github/workflows/ComposeAdvanced.yml
.github/workflows/ComposeStarter.yml
.github/workflows/DataLayer.yml
.github/workflows/WearSpeakerSample.yml
.github/workflows/WearStandaloneGoogleSignIn.yml
AlwaysOnKotlin/compose/build.gradle
AlwaysOnKotlin/compose/proguard-rules.pro
AlwaysOnKotlin/views/build.gradle
AlwaysOnKotlin/views/proguard-rules.pro
ComposeAdvanced/app/build.gradle
ComposeStarter/app/build.gradle
DataLayer/Wearable/build.gradle
DataLayer/Wearable/proguard-rules.pro
WearSpeakerSample/wear/build.gradle
WearStandaloneGoogleSignIn/app/build.gradle
WearStandaloneGoogleSignIn/app/proguard-rules.pro

Fixes https://github.com/android/wear-os-samples/issues/238#issuecomment-1065984919

Release builds for samples

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/util/ReportFullyDrawn.kt
ComposeAdvanced/benchmark/src/main/AndroidManifest.xml
ComposeAdvanced/benchmark/src/main/java/com/example/android/wearable/composeadvanced/benchmark/StartupBenchmark.kt

Add Report Fully Drawn to improve the benchmarks.

Report Fully Drawn

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/CustomTimeText.kt

With a temporary edit to flip isEmulator

Show warning for debug builds on devices

---

ComposeAdvanced/app/src/main/AndroidManifest.xml
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/map/MapActivity.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/map/MapScreen.kt
ComposeAdvanced/app/src/main/res/values/strings.xml

Show Map as a separate Activity

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/MainActivity.kt

Advice is for app to not use getDefaultViewModelProviderFactory directly, since it is easy to just create a val.

Avoid using getDefaultViewModelProviderFactory

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt

The Round Watch/Square Watch text at the bottom of the main screen is hard to read as it is purple on purple a lot of the time. So adding a gradient behind which also allows us to show how to do modifier/gradients in the curved world

Put a gradient under the Watch identifier

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt
ComposeAdvanced/app/src/main/res/values/strings.xml

Add a voice entry only sample.

Add voice entry sample.

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/MainActivity.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watch/WatchDetailScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watch/WatchDetailViewModel.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListViewModel.kt

Attempt to use the new view model functionality as nature intended.

View model cleanup

---

WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Alarm.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Media.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Meditation.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Run.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Workout.kt

Fixes #498 
Before | After
---|---

Fix clipped chips in tiles

---

WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileTheme.kt
WearTilesKotlin/gradle/libs.versions.toml

```
Caused by: java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..16)
at android.graphics.ColorSpace.get(ColorSpace.java:1390)
at android.graphics.Color.colorSpace(Color.java:704)
at android.graphics.Color.valueOf(Color.java:883)
at com.example.wear.tiles.messaging.MessagingTileTheme.<clinit>(MessagingTileTheme.kt:22)
```

Fix color space exception

---

WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/AnalogWatchCanvasRenderer.kt
WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/utils/ComplicationUtils.kt

#Fixes https://github.com/android/wear-os-samples/issues/523

Update deprecate methods in Watchface sample

---

WearTilesKotlin/settings.gradle

Maybe causing https://github.com/android/wear-os-samples/pull/488

Remove development repo

---

TimeText/gradle/libs.versions.toml

Reverts android/wear-os-samples#549

Revert "Update dependency com.android.application to v7.3.0"

---

DataLayer/Application/src/main/java/com/example/android/wearable/datalayer/MainActivity.kt

Replace usage of `NodeClient` by `CapabilityClient`.
https://github.com/android/wear-os-samples/issues/505

Replace usage of NodeClient by CapabilityClient

---

ComposeAdvanced/README.md
ComposeStarter/README.md
DataLayer/README.md
RuntimePermissionsWear/README.md
TimeText/README.md
WatchFaceKotlin/README.md
WearComplicationDataSourcesTestSuite/README.md
WearOAuth/README.md
WearSpeakerSample/README.md
WearStandaloneGoogleSignIn/README.md
WearTilesKotlin/README.md
WearVerifyRemoteApp/README.md

Change StackOverflow tag in README to `wear-os`.
Address https://github.com/android/wear-os-samples/pull/598#discussion_r1017843062

Change SO tag to wear-os

---

WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/MainState.kt
WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/SoundRecorder.kt

AudioRecord only supports PCM, MediaRecorder is a better sample as it supports Ogg Opus.

Opus recording

---

AlwaysOnKotlin/README.md

Contains a general refresh of the README that aims to increase clarity, improve grammar, and canonicalize best practices.

Restructure README to highlight best practices.

---

ComposeAdvanced/app/build.gradle
ComposeAdvanced/gradle/libs.versions.toml

Switch ComposeAdvanced sample to compose alpha versions

Use alpha versions for ComposeAdvanced sample

---

ComposeAdvanced/app/src/main/AndroidManifest.xml
ComposeAdvanced/app/src/main/res/values/styles.xml
ComposeAdvanced/gradle/libs.versions.toml

This reverts commit e79ada3e31d3cc6c0a9c9d9aef2594493c7f01fb.

Revert "Update core-splashscreen and simplify (#700)"

---

.github/workflows/ComposeAdvanced.yml
ComposeAdvanced/app/build.gradle
ComposeAdvanced/app/src/main/AndroidManifest.xml
ComposeAdvanced/gradle/libs.versions.toml

Want to try out the baselineprofile plugin https://developer.android.com/studio/preview/features#baseline-profiles-module-wizard
And before that want latest versions

Bump compose-advanced versions

---

.github/workflows/AlwaysOnKotlin.yml
AlwaysOnKotlin/gradle.properties

From https://github.com/android/wear-os-samples/pull/804#issuecomment-1546222380

AlwaysOnKotlin android.sdk.channel=3

---

AlwaysOnKotlin/gradle/libs.versions.toml
ComposeAdvanced/gradle/libs.versions.toml
ComposeStarter/gradle/libs.versions.toml
DataLayer/gradle/libs.versions.toml
RuntimePermissionsWear/gradle/libs.versions.toml
TimeText/gradle/libs.versions.toml
WatchFaceKotlin/gradle/libs.versions.toml
WearComplicationDataSourcesTestSuite/gradle/libs.versions.toml
WearOAuth/gradle/libs.versions.toml
WearSpeakerSample/gradle/libs.versions.toml
WearStandaloneGoogleSignIn/gradle/libs.versions.toml
WearTilesKotlin/gradle/libs.versions.toml
WearVerifyRemoteApp/gradle/libs.versions.toml

Reverts android/wear-os-samples#813

Revert "Update plugin com-diffplug-spotless to v6.19.0"

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/WatchAppChip.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/dialog/Dialogs.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/theme/ThemeScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt
ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListScreen.kt

Use Horologist Compose Material.
Less verbose + a11y fixes.

Use Horologist Compose Material

---

ComposeAdvanced/app/src/main/AndroidManifest.xml

Following Lint guidance and https://developer.android.com/training/wearables/apps/launcher

Task Affinity for Advanced sample

---

TimeText/timetext/build.gradle
TimeText/timetext/src/test/java/com/example/android/wearable/timetext/TimeTextTest.kt
TimeText/wear/build.gradle

Bump from https://github.com/android/wear-os-samples/pull/928

Timetext update

---

WearTilesKotlin/app/build.gradle
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileLayout.kt
WearTilesKotlin/gradle/libs.versions.toml

Fix Tile previews

---

WatchFaceFormat/Complications/res/raw/watchface.xml
WatchFaceFormat/SimpleAnalog/res/raw/watchface.xml
WatchFaceFormat/SimpleDigital/res/raw/watchface.xml

Samples contained use of redundant metadata item. Removing them.

Removes use of old metadata element

---

AlwaysOnKotlin/build.gradle
AlwaysOnKotlin/compose/build.gradle
AlwaysOnKotlin/compose/src/test/java/com/example/android/wearable/wear/alwayson/AlwaysOnUnitTests.kt
AlwaysOnKotlin/gradle.properties
AlwaysOnKotlin/gradle/libs.versions.toml

Add FTL devices to AlwaysOnKotlin

---

WatchFaceKotlin/README.md
WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/utils/ComplicationUtils.kt

Promotes use of Watch Face Format.

Updates messaging to recommend use of Watch Face Format

---

.github/workflows/AlwaysOnKotlin.yml
AlwaysOnKotlin/AlwaysOnKotlin.yml
AlwaysOnKotlin/compose/build.gradle
AlwaysOnKotlin/gradle.properties

https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/

Run on faster ubuntu runners

---

ComposeStarter/app/build.gradle
ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt
ComposeStarter/gradle/libs.versions.toml

RSB + TimeText + PositionIndicator + Responsive Layout

Fix ComposeStarter sample

---

ComposeStarter/README.md

Adds a description of the two techniques for verifying behavior with different screen sizes.

Adds device size testing documentation

---

ComposeStarter/app/src/main/res/values-round/themes.xml
ComposeStarter/app/src/main/res/values/themes.xml

Use Theme.SplashScreen.IconBackground. Still requires providing dimens, but adding Theme.SplashScreen.IconBackground to continue discussion.

Use Theme.SplashScreen.IconBackground

---

ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/MainActivity.kt
ComposeStarter/app/src/main/AndroidManifest.xml
ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt

I noticed two bugs with Sergio.
The splashscreen showed up on swipe to dismiss.
The time text didn't scroll away.

Fix splashscreen and warnings

---

ComposeAdvanced/README.md
RuntimePermissionsWear/README.md
TimeText/README.md
WearStandaloneGoogleSignIn/README.md
WearVerifyRemoteApp/README.md

Add deprecation warning to samples. Next step is to remove those samples from main.

Add deprecation warning to deprecated samples

---

.github/workflows/AlwaysOnKotlin.yml
AlwaysOnKotlin/README.md
AlwaysOnKotlin/compose/src/androidTest/java/com/example/android/wearable/wear/alwayson/AlwaysOnAppTests.kt
AlwaysOnKotlin/views/src/androidTest/java/com/example/android/wearable/wear/alwayson/MainActivityTests.kt

First step for solving #1036, there will be another PR for removing it from main.

Adds deprecation notice for views implementation in AlwaysOn sample

---

ComposeStarter/README.md

Fixes link for Horologist on Compose starter README

Fixes link for Horologist on Compose starter README

---

AlwaysOnKotlin/README.md

Update the warning to say that the entire sample is deprecated

---

WearComplicationDataSourcesTestSuite/Wearable/src/main/AndroidManifest.xml
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/Complication.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ComplicationToggleReceiver.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/GoalProgressDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/IconDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/LargeImageDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/LongTextDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/RangedValueDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ShortTextDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/SmallImageDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/WeightedElementsDataSourceService.kt
WearComplicationDataSourcesTestSuite/Wearable/src/main/res/values/strings.xml
WearComplicationDataSourcesTestSuite/gradle/libs.versions.toml

Updates Complication data source suite to add support for:
- GOAL_PROGRESS
- WEIGHTED_ELEMENTS
Data source types.

Adds support for GOAL_PROGRESS and WEIGHTED_ELEMENTS complications.

---

WatchFaceFormat/Complications/watchface/build.gradle.kts
WatchFaceFormat/Flavors/watchface/build.gradle.kts
WatchFaceFormat/SimpleAnalog/watchface/build.gradle.kts
WatchFaceFormat/SimpleDigital/watchface/build.gradle.kts
WatchFaceFormat/Weather/watchface/build.gradle.kts

Use a debug signing key so signed APKs are generated for local testing

Release build of Watchfaces

---

README.md
WearSpeakerSample/README.md
WearSpeakerSample/wear/build.gradle
WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/ControlDashboard.kt
WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/SpeakerRecordingScreen.kt

Further cleanup for #1041
This simplifies the layout removing ConstraintLayout.

Simplify layout of Speaker Sample

---

WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Media.kt
WearTilesKotlin/gradle/libs.versions.toml

Demonstrate a larger screen layout

---

ComposeStarter/README.md

Updates the README for the ComposeStarter sample to point to guidance for CI.

Adds link to CI guidance.

---

WearOAuth/oauth-device-grant/src/main/java/com/example/android/wearable/oauth/devicegrant/AuthDeviceGrantActivity.kt
WearOAuth/oauth-device-grant/src/main/java/com/example/android/wearable/oauth/devicegrant/AuthDeviceGrantViewModel.kt
WearOAuth/oauth-device-grant/src/main/res/values/strings.xml

Adds Compose preview to OAuth device grant

Adds Compose preview to OAuth device grant

---

WatchFaceFormat/Weather/watchface/src/main/res/raw/watchface.xml

Updates comments for weather sample to explain use of shorthand and point to general conditionals guidance.

Updated comments in Weather sample

---

DataLayer/README.md

I will fix the line break and a link in the readme.

fix DataLayer README

---

ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt

Remove `.fillMaxSize()`  from SLC modifier as it's default.

SLC has a default fill

---

WatchFaceFormat/Weather/watchface/src/main/res/raw/watchface.xml

Swapped snow / rain icons (11,12) to match conditions.
https://developer.android.com/training/wearables/wff/common/attributes/source-type
11 - LIGHT_SNOW
12 - LIGHT_RAIN

Swap Rain / Snow Icons in watchface.xml

---

WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Alarm.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Calendar.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Goal.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/GoldenTilesPreviewsRow1.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/GoldenTilesPreviewsRow2.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/GoldenTilesPreviewsRow3.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/HeartRate.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Media.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Meditation.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/News.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Run.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Ski.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Social.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Timer.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Weather.kt
WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Workout.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileLayout.kt
WearTilesKotlin/app/src/main/java/com/example/wear/tiles/tools/MultiDevicesPreviews.kt

I extracted common preview into custom annotation.

extract common preview into custom annotation

---

WatchFaceKotlin/app/build.gradle

Bumps targetSdk for `WatchFaceKotlin` to 34.

Bumps targetSdk to 34

---

ComposeStarter/gradle/libs.versions.toml
DataLayer/gradle/libs.versions.toml
WearOAuth/gradle/libs.versions.toml
WearSpeakerSample/gradle/libs.versions.toml

Update to Compose 1.4. No code changes since all samples are using Horologist.

Update to Compose 1.4

---

WatchFaceFormat/SimpleAnalog/watchface/src/main/res/raw/watchface.xml

Fixes incorrect syntax for `resources` attribute in WFF elements

Fixes resource syntax

---

renovate.json

Update renovate.json so that it updates to 0.6 Horologist version

Update renovate to trigger updates for Horologist 0.6

---

Complications/Wearable/src/main/AndroidManifest.xml

To unblock https://github.com/android/wear-os-samples/pull/1192

Define targetApi for complication services

---

WatchFaceFormat/README.md

Updates Readme for Watch Face Format samples
Lists additional Gradle tasks that can be run for validating WFF XML and installing to connected devices/emulators.

Updates WFF Readme

---

DataLayer/Application/build.gradle.kts
DataLayer/gradle/libs.versions.toml

Update (Phone) Datalayer compile target 35 for compatibility with newest libraries

Update (Phone) Datalayer compile target 35

---

DataLayer/Wearable/build.gradle.kts
DataLayer/gradle/libs.versions.toml
WearSpeakerSample/gradle/libs.versions.toml
WearSpeakerSample/wear/build.gradle.kts
WearSpeakerSample/wear/src/test/java/com/example/android/wearable/speaker/SpeakerRecordingScreenTest.kt

- Update dependency to Horologist and Robolectric to fix tests
- Update compile target to 35

Update Robolectric libraries to fix tests

---

Complications/build.gradle.kts
Complications/gradle/libs.versions.toml

Update kotlin and kotlinx versions in Complications to fix https://github.com/android/wear-os-samples/pull/1232 and some refactoring in the build.gradle

Update kotlin in Complications sample

---

WatchFaceFormat/Complications/build.gradle.kts
WatchFaceFormat/Complications/watchface/build.gradle.kts
WatchFaceFormat/Flavors/build.gradle.kts
WatchFaceFormat/Flavors/watchface/build.gradle.kts
WatchFaceFormat/SimpleAnalog/build.gradle.kts
WatchFaceFormat/SimpleAnalog/watchface/build.gradle.kts
WatchFaceFormat/SimpleDigital/build.gradle.kts
WatchFaceFormat/SimpleDigital/watchface/build.gradle.kts
WatchFaceFormat/Weather/build.gradle.kts
WatchFaceFormat/Weather/watchface/build.gradle.kts

Removes unnecessary plugins from Watch Face samples.

Removes unnecessary plugins

---

WatchFaceFormat/validator-plugin/gradle/libs.versions.toml

Fixes kotlin compatibility issue when building watch faces validator plugin

Fixes kotlin version compatibility

---

renovate.json

Does this configuration cover it?

Ignores renovate rule for Kotlin in the case of Watch Face Format samples

---

WatchFaceFormat/Complications/watchface/src/main/AndroidManifest.xml
WatchFaceFormat/Flavors/watchface/src/main/AndroidManifest.xml
WatchFaceFormat/SimpleAnalog/watchface/src/main/AndroidManifest.xml
WatchFaceFormat/SimpleDigital/watchface/src/main/AndroidManifest.xml
WatchFaceFormat/Weather/watchface/src/main/AndroidManifest.xml

Adds standalone declaration for watch faces

Adds standalone declaration

---

ComposeStarter/app/build.gradle.kts
ComposeStarter/app/src/main/AndroidManifest.xml
ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt
ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/theme/WearAppTheme.kt
ComposeStarter/gradle/libs.versions.toml

On API 36 use dynamic colour schemes

Support dynamic color schemes.

---

ComposeStarter/app/build.gradle.kts
ComposeStarter/build.gradle.kts
ComposeStarter/gradle/libs.versions.toml
DataLayer/Application/build.gradle.kts
DataLayer/Wearable/build.gradle.kts
DataLayer/gradle/libs.versions.toml
WearOAuth/gradle/libs.versions.toml
WearSpeakerSample/gradle/libs.versions.toml

Update libraries in M3 branch in preparation for merging M3 to main

Update libraries in M3 branch
