android/wear-os-samples

- WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/config/DigitalWatchFaceConfigListenerService.java
- WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/config/DigitalWatchFaceWearableConfigActivity.java
- WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/util/DigitalWatchFaceUtil.java
- WatchFace/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/DigitalWatchFaceService.java
Without this, there is a race between the time DataItem is being written and the fetch which happens right after the config activity closes.
> Close the WatchFace config activity only after the DataItem is written.

- AlwaysOn/Wearable/src/main/AndroidManifest.xml
- RuntimePermissionsWear/Wearable/src/main/AndroidManifest.xml
- WearDrawers/Wearable/src/main/AndroidManifest.xml
- WearSpeakerSample/wear/src/main/AndroidManifest.xml
- WearStandaloneGoogleSignIn/app/src/main/AndroidManifest.xml
- WearVerifyRemoteApp/Wearable/src/main/AndroidManifest.xml
Removes a no-longer relevant `AndroidManifest` entry from all samples that had it for supporting API levels before API 22.
> [All] Remove pre-22 AndroidManifest flag

- AlwaysOn/Wearable/src/main/AndroidManifest.xml
A partial revert of #95. Without this tag, `AlwaysOn` will currently crash on startup with an `IllegalStateException`. The other samples where this tag was explicitly removed still have the tag included in their manifests via the dependency on `com.google.android.support:wearable:2.8.1`
>  [AlwaysOn] Re-add uses-library tag

- AlwaysOn/Wearable/build.gradle
Adds a flag to Kotlin compilation to fail upon any compile warnings. There are none right now, but this would require addressing things like deprecation warnings in order to successfully build.
> [AlwaysOn] Treat Kotlin warnings as errors

- WearTilesKotlin/app/build.gradle
- WearTilesKotlin/build.gradle
Updates the tiles library to the latest version.
One interesting note:
Updating without bumping `kotlinx-coroutines-guava` caused a runtime crash in the renderer along the lines of
```
java.lang.NoSuchMethodError: No direct method <init>(Lkotlin/coroutines/CoroutineContext;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lkotlinx/coroutines/AbstractCoroutine; or its super classes (declaration of 'kotlinx.coroutines.AbstractCoroutine' appears in /data/app/...
```
I'm guessing this was due to the version bump of `kotlinx.coroutines` in `androidx` to `1.5.0`. This bumped `kotlinx-coroutines-android` and `kotlinx-coroutines-core` to `1.5.0`, but left `kotlinx-coroutines-guava` on `1.4.2`.
Updated the Kotlin version and `kotlinx-coroutines` version to latest.
> [Tiles] Update to alpha08

- AlwaysOnKotlin/Wearable/build.gradle
- AlwaysOnKotlin/build.gradle
Bumps the `AlwaysOn` dependencies to latest, including to the latest alpha of the `androidx.wear` library.
> [AlwaysOn] Update dependencies

- DataLayer/Application/build.gradle
- DataLayer/Wearable/build.gradle
- RuntimePermissionsWear/Application/build.gradle
- RuntimePermissionsWear/Shared/build.gradle
- RuntimePermissionsWear/Wearable/build.gradle
- WatchFace/Application/build.gradle
- WatchFace/Wearable/build.gradle
- WatchFaceAlphaKotlin/build.gradle
- WearAccessibilityApp/Wearable/build.gradle
- WearDrawers/Wearable/build.gradle
- WearStandaloneGoogleSignIn/build.gradle
- WearTilesKotlin/build.gradle
Replaces jcenter with mavenCentral for all remaining places in this repo!
Verified via `./gradlew check` that each affected project still built with the repository update.
> Remove jcenter

- AlwaysOnKotlin/Wearable/build.gradle
- AlwaysOnKotlin/Wearable/src/main/AndroidManifest.xml
Updates `AlwaysOn` to the latest version of `android.wear`, `alpha12`.
Due to https://android-review.googlesource.com/c/platform/frameworks/support/+/1749800/, this allows removing the tag from our `AndroidManifest.xml`.
> [AlwaysOn] Update to androidx.wear alpha12

- AlwaysOnKotlin/Wearable/build.gradle
- AlwaysOnKotlin/Wearable/src/androidTest/java/com/example/android/wearable/wear/alwayson/MainActivityTests.kt
- AlwaysOnKotlin/Wearable/src/main/java/com/example/android/wearable/wear/alwayson/MainActivity.kt
- AlwaysOnKotlin/build.gradle
- AlwaysOnKotlin/spotless/copyright.kt
- RuntimePermissionsWear/build.gradle
- RuntimePermissionsWear/spotless/copyright.kt
- WearComplicationProvidersTestSuite/Wearable/build.gradle
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ComplicationToggleArgs.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ComplicationToggleReceiver.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/DataStorage.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/IconProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/LargeImageProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/LongTextProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/NoDataProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/RangedValueProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/ShortTextProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/SmallImageProviderService.kt
- WearComplicationProvidersTestSuite/Wearable/src/main/java/com/example/android/wearable/wear/wearcomplicationproviderstestsuite/SuspendingComplicationProviderService.kt
- WearComplicationProvidersTestSuite/build.gradle
- WearComplicationProvidersTestSuite/spotless/copyright.kt
- WearSpeakerSample/build.gradle
- WearSpeakerSample/spotless/copyright.kt
- WearSpeakerSample/wear/build.gradle
- WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/MainActivity.kt
- WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/MainViewModel.kt
- WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/MotionLayoutExt.kt
- WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/SoundRecorder.kt
- WearVerifyRemoteApp/build.gradle
- WearVerifyRemoteApp/spotless/copyright.kt
Adds `spotless` to the recently updated samples, and also applies it to those that have been converted to Kotlin.
In particular, `AlwaysOn`, `Speaker`, and `Complications` all got spotless and had it applied, whereas `RuntimePermissions` and `VerifyRemote` just had it added.
I also updated a few dependencies so that `lint` was happy.
> Add spotless to updated samples

- WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt
- WearVerifyRemoteApp/Wearable/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainWearActivity.kt
Fixes the handling of `CancellationException`s in `VerifyRemote`.
We still don't want to catch them in our `throwable: Throwable` block, but we also don't want to eat them. We should instead rethrow the exception again to allow cancellation to propogate.
> [VerifyRemote] Fix handling of CancellationExceptions

- WatchFaceAlphaKotlin/app/src/main/AndroidManifest.xml
This has been renamed to androidx.wear.watchface.MockTime and is
registered programmatically in the library.
> Remove outdated MockTime intent filter.

- WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt
Passes the list of nodes to the formatted string, which previously was displaying the placeholder: `%1$s`
> [VerifyRemote] Pass nodes to formatted string

- WearSpeakerSample/timetext/build.gradle
- WearSpeakerSample/timetext/src/main/AndroidManifest.xml
- WearSpeakerSample/timetext/src/main/java/com/example/android/wearable/timetext/TextViewWrapper.kt
- WearSpeakerSample/timetext/src/main/java/com/example/android/wearable/timetext/TimeText.kt
- WearSpeakerSample/timetext/src/main/res/layout/curved_time_text.xml
- WearSpeakerSample/timetext/src/main/res/layout/straight_time_text.xml
- WearSpeakerSample/timetext/src/main/res/values/attrs.xml
- WearSpeakerSample/timetext/src/main/res/values/dimens.xml
- WearSpeakerSample/timetext/src/main/res/values/styles.xml
- WearSpeakerSample/timetext/src/test/java/com/example/android/wearable/timetext/CurvedWithTextMatcher.kt
- WearSpeakerSample/timetext/src/test/java/com/example/android/wearable/timetext/TimeTextTest.kt
- WearSpeakerSample/timetexttestsupport/build.gradle
- WearSpeakerSample/timetexttestsupport/src/main/AndroidManifest.xml
- WearSpeakerSample/timetexttestsupport/src/main/java/com/example/android/wearable/timetext/TestActivity.kt
- WearSpeakerSample/wear/src/main/res/layout/main_activity.xml
Adds a `TimeText` library module to the speaker sample, which provides a standardized way to display the time on all overlays, as recommended in the design guidelines for Wear OS apps: https://developer.android.com/training/wearables/design/overlays#time
The `TimeText` is equipped to be displayed on both round and non-round devices, as well as display a title accompanying the time.
For being able to showcase it, I've added this to the speaker sample, which pulls in the library to display the time.
> Add TimeText

- WearOAuth/build.gradle
- WearOAuth/gradle/wrapper/gradle-wrapper.properties
- WearOAuth/oauth-device-grant/build.gradle
- WearOAuth/oauth-pkce/build.gradle
- WearOAuth/oauth-pkce/src/main/java/com/example/android/wearable/oauth/pkce/AuthPKCEViewModel.kt
Updates dependencies to latest for the OAuth sample. This also updates to use `OAuthRequest.redirectUrl`, rather than manually constructing it in the same way as done in the `androidx` library.
> [OAuth] Update dependencies

- AlwaysOnKotlin/compose/src/main/java/com/example/android/wearable/wear/alwayson/AlwaysOnScreen.kt
- ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt
- DataLayer/Wearable/src/main/java/com/example/android/wearable/datalayer/MainApp.kt
- WearSpeakerSample/wear/src/main/java/com/example/android/wearable/speaker/SpeakerScreen.kt
Starting with Android Studio Dolphin, showSystemUi option controls if
the device frame/clip should be applied.
> Set @Preview options for full page previews

- WatchFaceKotlin/app/src/main/res/values/strings.xml
The descriptions strings are not actually limited to 20 characters,
and it wasn't respected anyway.
> Remove false char limits

- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/navigation/DestinationScrollType.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/navigation/Screen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/progressindicator/ProgressIndicators.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt
- ComposeAdvanced/app/src/main/res/values/strings.xml
Add an example of a spinner and a full screen progress indicator to the sample.
Add a new type of destination scroll type for time text only.
Fix up out of date comment in UserInputComponentsScreen.kt
> Add progress indicator examples to compose advanced

- ComposeAdvanced/app/build.gradle
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt
- ComposeAdvanced/app/src/main/res/values/strings.xml
- ComposeAdvanced/gradle/libs.versions.toml
Provide an example of getting text input from the user using RemoteInputIntentHelper. At the moment this is the only reliable way of getting text input as there are known issues with the foundation compose BasicTextField
.
> Add an example of getting text input from a RemoteInputIntentHelper

- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/navigation/Screen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/theme/Color.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/theme/Theme.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/theme/ThemeScreen.kt
- ComposeAdvanced/app/src/main/res/values/strings.xml
Give the user access to 4 different theme alternatives and a way to select them in the app
.
> Add dynamic/selectable theme support to the Advanced Compose add.

- .github/workflows/AlwaysOnKotlin.yml
26 and 28 are working, but don't meet test requirements.
> Only run AlwaysOnKotlin on 28

- WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileTheme.kt
Instead of defining Tile colors explicitly, transform from a compose color palette, since that'll be the usual case (compose-based Wear app + tile + ...)
No changes outside this file (Colors is still accessed via `MessagingTileTheme.colors`).
> Use Compose colors for tiles sample

- RuntimePermissionsWear/Application/build.gradle
- RuntimePermissionsWear/gradle/libs.versions.toml
- Bump targetSDK to 33
- Use newer version of play-services-wearable library with added support for apps targeting Android13
> Fix for Android13 compatibility issue (#435)

- DataLayer/Wearable/src/main/java/com/example/android/wearable/datalayer/MainActivity.kt
Change `MainActivity` in `Wearable` app of `DataLayer` project to make use of the [defined constants](https://github.com/android/wear-os-samples/blob/5e3c9971097fb212c40a4bfae2a567bd8afc8791/DataLayer/Wearable/src/main/java/com/example/android/wearable/datalayer/MainActivity.kt#L136-L138) in the class.
In order to improve readability.
This was probably the intention when the constants were introduced in https://github.com/android/wear-os-samples/pull/200.
> [DataLayer] Make use of defined constants

- DataLayer/Application/build.gradle
Remove from the mobile app module, the dependency on the wear app module with `wearApp` configuration.
It does seem to be needed. Tested the app without it and it works fine.
The only place in the [documentation](https://developer.android.com/studio/build/dependencies#wear_apps) that I could find reference to this configuration seems to not explain why it is needed.
Related: #585
> #585 Remove dependency with wearApp configuration

- WearVerifyRemoteApp/Wearable/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainWearActivity.kt
Remove unused code from `MainWearActivity`.
Somehow related: https://github.com/android/wear-os-samples/issues/505
> [WearVerifyRemoteApp] Remove unused code

- WearStandaloneGoogleSignIn/README.md
Update support topic in README of `WearStandaloneGoogleSignIn` module.
Based on this blog [post](https://android-developers.googleblog.com/2017/01/final-android-wear-20-developer-preview.html) from 2017, it looks like "Android Wear Developers Community" was a Google plus [community](https://plus.google.com/communities/113381227473021565406) which is no longer.
Other [samples](https://github.com/android/wear-os-samples/blob/34959564394966395ccd2c6c174e6612c2adac96/AlwaysOnKotlin/README.md?plain=1#L50) have SO as support.
> [WearStandaloneGoogleSignIn] Update support topic in README

- TimeText/gradle.properties
- TimeText/timetext/src/main/AndroidManifest.xml
- TimeText/timetexttestsupport/build.gradle
- WearOAuth/util/build.gradle
Fix/Ignore `ExpiredTargetSdkVersion` lint error.
Fixes #602 
- Add `android.hardware.type.watch` to `TimeText` as it seems to be a wear specific module;
- Bump `targetSdk` to 31 for `WearOAuth/util` and `TimeText/timetexttestsupport` as they seem to be a non-wear specific modules;
- Increase memory in `gradle.properties` from `TimeText` due to issue in CI when running `:wear:lintAnalyzeDebug`:
```
* Exception is:
java.lang.OutOfMemoryError: Metaspace
```
> Fix ExpiredTargetSdkVersion lint error

- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/benchmark/ScrollActivity.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/theme/ThemeScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListScreen.kt
In v1.1 `ToggleChip` support usage of animated toggle controls (`Checkbox`, `Switch` and `RadioButton`) that can be used instead of the static icons provided by `ToggleChipDefaults`.
> Use animated toggle controls in ToggleChips

- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/dialog/Dialogs.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/progressindicator/ProgressIndicators.kt
Demos for a new features available in Compose for Wear OS version 1.1:
- Using Outlined style for Chips at `Dialogs` screen
- Example of modifying Chip shape at `Progress Indicators` screen
> Demos for Outlined style for Chips and modifying Chip shape

- AlwaysOnKotlin/compose/build.gradle
- AlwaysOnKotlin/gradle/libs.versions.toml
Thanks for a very cool sample repo! I really like it! :) 
Starting to use the Compose BoM for the AlwaysOnKotlin project. My plan is to add a PR for each project in this repo to migrate to use the Compose BoM.
I was not 100% sure if it is the best approach to separate it into one PR for each project vs one PR for everything. However, I felt that it might be a bit easier to review it then. 
Issue is relating to #584  although it is the December version not October now.
> [AlwaysOnKotlin] Migrate to December version of Compose BoM for AlwaysOnKotlin

- ComposeAdvanced/app/build.gradle
- ComposeAdvanced/gradle/libs.versions.toml
Start using the December BoM for Compose dependencies in the ComposeAdvanced sample.
Following up #631 relating to #584
> [ComposeAdvanced] Start using the December BoM for Compose dependencies

- WearStandaloneGoogleSignIn/app/build.gradle
- WearStandaloneGoogleSignIn/gradle/libs.versions.toml
Start using the December BoM for Compose dependencies in the WearStandaloneGoogleSignIn project. 
Following up #631 relating to #584 
According to the Readme, this should be the last project in this repo that uses compose so, if this PR gets merged the last, this should resolve #584 :)
> [WearStandaloneGoogleSignIn] Start using the December BoM for Compose  dependencies

- WearSpeakerSample/gradle/libs.versions.toml
- WearSpeakerSample/wear/build.gradle
Start using the December BoM for Compose dependencies on the WearSpeakerSample project.
Following up #631 relating to #584
> [WearSpeakerSample] Start using the December BoM for Compose dependencies

- DataLayer/Application/build.gradle
- DataLayer/Wearable/build.gradle
- DataLayer/gradle/libs.versions.toml
Migrate to the December version of the BoM for Compose dependencies in the DataLayer project.
Following up #631 relating to #584
> [DataLayer] Start using the December Compose BoM for Compose dependencies

- ComposeStarter/app/build.gradle
- ComposeStarter/gradle/libs.versions.toml
Start using the December BoM for the Compose dependencies in the Compose Starter project.
Following up #631 relating to #584
> [ComposeStarter] Use December BoM for Compose dependencies

- RuntimePermissionsWear/Application/build.gradle
Remove from the mobile app module of the `RuntimePermissionsWear` sample, the dependency on the wear app module with `wearApp` configuration.
It does seem to be needed. I did **not** test the app after the changes, but the other apps were still working fine after it was removed in https://github.com/android/wear-os-samples/pull/586 and https://github.com/android/wear-os-samples/pull/589. Also, the only place in the [documentation](https://developer.android.com/studio/build/dependencies#wear_apps) that I could find reference to this configuration was updated this morning, removing the reference.
Fixes #585
> [RuntimePermissionsWear] Remove dependency with wearApp configuration

- AlwaysOnKotlin/compose/build.gradle
If `com.google.android.wearable:wearable:2.9.0` isn't specified then the ambient mode won't be triggered in release mode
> [AlwaysOnKotlin] add missing dependency for release

- ComposeAdvanced/app/build.gradle
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
- ComposeAdvanced/gradle/libs.versions.toml
Fix display of switch controls in `ToggleChip` in RTL in ComposeAdvanced sample.
| Before | After |
|--------|--------|
|![ToggleChip_RTL_before](https://github.com/android/wear-os-samples/assets/878134/c7242cef-1fe6-4351-aac0-0aad82982e68) |![ToggleChip_RTL_after](https://github.com/android/wear-os-samples/assets/878134/6e4f5712-3fda-414c-a934-4356450948a4) | 
The switch control is displaying on the wrong direction in RTL.
Use `ToggleChip` from Horologist [Compose Material](https://github.com/google/horologist/tree/main/compose-material).
> [ComposeAdvanced] Fix ToggleChip in RTL

- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/WearApp.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/components/CustomTimeText.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/navigation/Screen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/dialog/Dialogs.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/landing/LandingScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/map/MapScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/progressindicator/ProgressIndicators.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/theme/ThemeScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watch/WatchDetailScreen.kt
- ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/watchlist/WatchListScreen.kt
ComposeAdvanced shows too much flexibility, and has it's own homegrown concept for managing scaffold state.
Replace that with horologist.  
Reasons
1. Simplifies the code
2. The layout is much better
3. The default scroll behaviour is richer with haptics
https://github.com/android/wear-os-samples/assets/231923/325915ec-1c8d-4b86-b087-e1cf1fb3aec8
> Use Horologist WearNavScaffold

- WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/editor/WatchFaceConfigActivity.kt
Renames editor preview function name for clarity and fixes looping bug
- Updates `updateWatchFacePreview` to `updateWatchFaceEditorPreview`
- Fixes occasional infinite loop on minute hand slider: UI updates states updates UI updates state etc...
> Renames editor preview function name for clarity and fixes looping bug

- WatchFaceFormat/SimpleDigital/res/raw/watchface.xml
`Template` must have at least 1 `Parameter` element, even though the renderer may work without.
Resources should be specified without the `@string` prefix.
> Updates use of Template to use Parameter to ensure valid WFF

- WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/editor/WatchFaceConfigActivity.kt
- WatchFaceKotlin/app/src/main/res/layout/activity_watch_face_config.xml
focus on scroll view when creating watch config activity to easily support rotary input from crown
> focus on scroll view when creating watch config activity

- WatchFaceFormat/README.md
Adds a link from the `WatchFaceFormat` sample to the validator tools in the [watchface](https://github.com/google/watchface) repo.
> Adds links to WFF validator

- AlwaysOnKotlin/gradle.properties
It's no longer necessary now that AGP has been updated to 8.3.X, and it causes errors when updating AGP to 8.4.0-alpha05 or higher.
See https://issuetracker.google.com/issues/331681802
> Remove lint version from gradle.properties

- Complications/README.md
- WatchFaceKotlin/README.md
Adds notice regarding watch face development changes
> Adds notice regarding watch face development changes

- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Alarm.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Calendar.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/GoldenTilesPreviewsRow2.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/GoldenTilesPreviewsRow3.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Meditation.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/News.kt
- WearTilesKotlin/app/src/debug/java/com/example/wear/tiles/golden/Timer.kt
I applied responsive tiles to alarm, calendar, news, timer, meditation.
> apply responsive tiles to alarm, calendar, news, timer, mediation

- WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileLayout.kt
- WearTilesKotlin/app/src/main/java/com/example/wear/tiles/messaging/MessagingTileRenderer.kt
1. Is this the right API? (c.f. Horologist's [drawableResToImageResource()](https://github.com/google/horologist/blob/27802d54d07ca17061b6a13185c77586bc6c5f02/tiles/src/main/java/com/google/android/horologist/tiles/images/DrawableResToImageResource.kt#L28) approach.)
2. Is this the right place to put it? (Should it be in `tools/`?)
3. What happens if Tiles just adds this in a future release (as a regular method)? This code will error at compile time but … that's probably okay?
> Support drawables "directly"

- DataLayer/Wearable/src/main/res/raw/wear_keep.xml
In reference to https://github.com/google/horologist/pull/2385#issuecomment-2349196318 adding the wear_keep file to the raw folder in the wear sample. From what I understand from https://issuetracker.google.com/issues/348688201#comment4 this is needed for the resource shrinker to work.
> Add wear_keep file to wear datalayer sample

- WatchFaceFormat/validator-plugin/plugins/src/main/kotlin/AdbInstallTask.kt
- WatchFaceFormat/validator-plugin/plugins/src/main/kotlin/MemoryFootprintTask.kt
- WatchFaceFormat/validator-plugin/plugins/src/main/kotlin/ValidateWffFilesTask.kt
- WatchFaceFormat/validator-plugin/plugins/src/main/kotlin/WffToolDownloadTask.kt
- WatchFaceFormat/validator-plugin/plugins/src/main/kotlin/WffValidatorPlugin.kt
Adds an additional gradle task, to enable running the [Memory footprint evaluator](https://github.com/google/watchface/tree/main/play-validations).
Not run by default on each build, unlike the WFF validator, invoked using `./gradlew memoryFootprint`.
> Adds support for Memory Footprint tool

- .github/workflows/Complications.yml
- .github/workflows/ComposeStarter.yml
- .github/workflows/DataLayer.yml
- .github/workflows/WearOAuth.yml
- .github/workflows/WearSpeakerSample.yml
- .github/workflows/WearTilesKotlin.yml
- .github/workflows/copy-branch.yml
This PR standardizes GitHub Actions triggers in workflow files within `.github/workflows/`.
The goal is to ensure workflows run consistently on `push`, `pull_request`, and `workflow_dispatch` events where appropriate.
This is part of a batch of pull requests across repositories owned by the `android` organization on GitHub.
**Project Owner:** Please review the changes carefully to ensure they are correct and appropriate for this project before approving and merging.
* If you do not think this change is appropriate (e.g., a workflow should NOT run on one of these triggers), please leave a comment explaining why.
* If you think the goal is appropriate but notice a mistake in the implementation, please leave a comment detailing the mistake.
> Add triggers to .github/workflows/
